DROP TABLE IF EXISTS ROUTE;

CREATE TABLE ROUTE (
  ROUTEID VARCHAR PRIMARY KEY,
  ROUTENAME VARCHAR(250) NOT NULL,
  SOURCE VARCHAR(250) NOT NULL,
  DESTINATION VARCHAR(250) NOT NULL,
  STATIONS VARCHAR(500) NOT NULL
);

DROP TABLE IF EXISTS METRO;

CREATE TABLE METRO (
  METROKEY VARCHAR PRIMARY KEY,
  METROID VARCHAR(250) NOT NULL,
  ROUTEID VARCHAR(250) NOT NULL,
  NOOFCOACHES VARCHAR(250) NOT NULL,
  CROWDEDSTATUS VARCHAR(250) NOT NULL,
  CURRENTSTATION VARCHAR(250) NOT NULL,
  NEXTSTATION VARCHAR(250) NOT NULL
);


DROP TABLE IF EXISTS METROCOACH;

CREATE TABLE METROCOACH (
  COACHID VARCHAR PRIMARY KEY,
  COACHNAME VARCHAR(250) NOT NULL,
  METROID VARCHAR(250) NOT NULL,
  CAPACITY INT NOT NULL,
  FREESEATS INT NOT NULL
);

DROP TABLE IF EXISTS CUSTOMER;

CREATE TABLE CUSTOMER (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  surname VARCHAR(250) NOT NULL
);